<?php 
require ("inc/header_session.php");
require ("mainfunctions/database.php");
require ("mainfunctions/general-functions.php");

// Start Processing Function

//ZF Updated picklist per production MGR on 8/14/17

$today = date('m/d/y h:i a'); 

$user = $_COOKIE['userinitials'];


$last_load=1;

$last_load_qry = "SELECT load_number FROM loop_transaction_buyer WHERE warehouse_id = 32 order by load_number desc limit 1";

db();
$last_load_res = db_query($last_load_qry);

while ($last_load_row = array_shift($last_load_res)) {

	$last_load = $last_load_row["load_number"];

	$last_load = $last_load + 1;

}



$qry_newtrans = "INSERT INTO loop_transaction_buyer SET load_number = '" . $last_load . "', warehouse_id = '32', rec_type = 'Supplier', start_date = '" . $today . "', trans_type = 'Seller', tran_status = 'Pickup', employee = '" . $user . "', so_entered = 1,  so_employee = '" . $user . "', so_date = '" . date("m/d/Y") . "' ";

db();
$res_newtrans = db_query($qry_newtrans);



$idqry = "SELECT * FROM loop_transaction_buyer WHERE start_date LIKE '" . $today . "' ORDER BY id DESC";

db();
$res = db_query($idqry);

$row = array_shift($res);



srand ((int) microtime(true)*1000000);

$random_number = rand( );

$sql_sort = "INSERT INTO loop_salesorders  (so_date, warehouse_id, location_warehouse_id, trans_rec_id, box_id, qty, employee, rand_value, notes ) VALUES ( '" . date("m/d/Y") . "', '32', '18', '" . $row["id"] . "', '3307', '1', '" . $user . "', '" . $random_number . "', 'Recycling Order generated by System. Please contact company for pickup.')";

db();
$result_sort = db_query($sql_sort);



srand ((int) microtime(true)*1000000);

$random_number = rand( );

$sql_sort = "INSERT INTO loop_salesorders  (so_date, warehouse_id, location_warehouse_id, trans_rec_id, box_id, qty, employee, rand_value, notes ) VALUES ( '" . date("m/d/Y") . "', '32', '18', '" . $row["id"] . "', '3310', '1', '" . $user . "', '" . $random_number . "', 'Recycling Order generated by System. Please contact company for pickup.')";

db();
$result_sort = db_query($sql_sort);



srand ((int) microtime(true)*1000000);

$random_number = rand( );

$sql_sort = "INSERT INTO loop_salesorders  (so_date, warehouse_id, location_warehouse_id, trans_rec_id, box_id, qty, employee, rand_value, notes ) VALUES ( '" . date("m/d/Y") . "', '32', '18', '" . $row["id"] . "', '3306', '1', '" . $user . "', '" . $random_number . "', 'Recycling Order generated by System. Please contact company for pickup.')";

db();
$result_sort = db_query($sql_sort);



echo "<DIV CLASS='SQL_RESULTS'>Record Inserted<br><br>Please wait - the database is being updated and this page will automatically refresh.</DIV>";



	$returnurl = "huntvalleywarehouse_159265234358979.php";



	echo "<script type=\"text/javascript\">";

	echo "window.location.href=\"" . $returnurl . "\";";

	echo "</script>";

	echo "<noscript>";

	echo "<meta http-equiv=\"refresh\" content=\"0;url=\"". $returnurl . "\" />";

	echo "</noscript>"; exit;



?>